server:
  port: 8888
app:
  api:
    prefix: /api/v1
spring:
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8761
          predicates:
            - Path=${app.api.prefix}/**
#          FILTER S? B? QUA PREFIX VÍ D?: /API/EXAMPLE THÌ S? B? QUA /API
          filters:
            - StripPrefix=2